---
- include: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Update {{ kube_script_dir }} if this is atomic
  set_fact:
    kube_script_dir: "/usr/local/libexec/kubernretes"
  when: is_atomic and kube_script_dir == "/usr/libexec/kubernetes"

- name: Create kubernetes config directory
  file: path={{ kube_config_dir }} state=directory

- name: Create kubernetes script directory
  file: path={{ kube_script_dir }} state=directory

- name: write the global config file
  template: src=config.j2 dest={{ kube_config_dir }}/config
  notify:
    - restart daemons

- include: secrets.yml
  tags:
    secrets
