- name: Set pyyaml package name
  set_fact:
    pyyaml_name: python-yaml

- name: Overwrite pyyaml package name for non-Debian
  set_fact:
    pyyaml_name: PyYAML
  when: ansible_distribution != "Debian"

- name: Install PyYAML for non-debian
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: "{{ pyyaml_name }}"
    state: latest
