---
- name: Assures /etc/kubernetes/addons/ dir exists
  file: path=/etc/kubernetes/addons/ state=directory

- include: generic-install.yml
  when: not is_atomic

- name: Assures local addon dir exists
  local_action: file
    path={{ local_temp_addon_dir }}
    state=directory
  sudo: no

- name: Make sure the system services namespace exists
  get_url:
    url=https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/saltbase/salt/kube-addons/namespace.yaml
    dest="{{ kube_config_dir }}/addons/"
    force=yes

- include: dns.yml
  when: dns_setup

- include: cluster-monitoring.yml
  when: cluster_monitoring

- include: cluster-logging.yml
  when: cluster_logging

#- name: Get kube-addons script from Kubernetes
#  get_url:
#    url=https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/saltbase/salt/kube-addons/kube-addons.sh
#    dest={{ kube_script_dir }}/kube-addons.sh mode=0755
#    force=yes

#- name: Get kube-addon-update script from Kubernetes
#  get_url:
#    url=https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/saltbase/salt/kube-addons/kube-addon-update.sh
#    dest={{ kube_script_dir }}/kube-addon-update.sh mode=0755
#    force=yes

- name: HACK | copy local kube-addons.sh
  copy: src=kube-addons.sh dest={{ kube_script_dir }}/kube-addons.sh mode=0755

- name: HACK | copy local kube-addon-update.sh
  copy: src=kube-addon-update.sh dest={{ kube_script_dir }}/kube-addon-update.sh mode=0755

- name: Run kube-gen-token script to create {{ kube_token_dir }}/known_tokens.csv
  command: "{{ kube_script_dir }}/kube-gen-token.sh {{ item }}"
  environment:
    TOKEN_DIR: "{{ kube_token_dir }}"
  with_items:
    - "system:dns"
    - "system:monitoring"
    - "system:logging"
  register: gentoken
  changed_when: "'Added' in gentoken.stdout"
  notify:
    - restart apiserver
    - restart kube-addons

- name: Install kube-addons service
  template: src=kube-addons.service.j2 dest=/etc/systemd/system/kube-addons.service
  notify:
    - reload and restart kube-addons

- name: Enable and start kube addons
  service: name=kube-addons.service enabled=yes state=started
