---
- name: Open firewalld port for apiserver
  firewalld: port={{ kube_master_api_port }}/tcp permanent=false state=enabled
  # in case this is also a node with firewalld turned off
  ignore_errors: yes

- name: Save firewalld port for apiserver
  firewalld: port={{ kube_master_api_port }}/tcp permanent=true state=enabled
  # in case this is also a node with firewalld turned off
  ignore_errors: yes
