---
- name: Get iptables rules
  command: iptables -L
  register: iptablesrules
  always_run: yes

- name: Open apiserver port with iptables
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 8080 -j ACCEPT -m comment --comment "kube-apiserver"
  when: kube-apiserver not in iptablesrules.stdout
  notify:
          - restart iptables

- name: Save iptables rules
  command: service iptables save
  when: kube-apiserver not in iptablesrules.stdout
