version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11.1
    working_directory: /go/src/github.com/islinwb/kubernetes
    steps:
    - checkout
    - run: cd cmd/kubectl
    - run: go build
  test:
    docker:
    - image: circleci/golang:1.11.1
    working_directory: /go/src/github.com/islinwb/kubernetes
    steps:
    - checkout
    - run: cd pkg/controller
    - run: go test
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test
