---
- name: restart flannel
  service: name=flanneld state=restarted
  notify:
    - stop docker
    - delete docker0
    - start docker
  when: inventory_hostname in groups['nodes']

- name: stop docker
  service: name=docker state=stopped

- name: delete docker0
  command: ip link delete docker0
  ignore_errors: yes

- name: start docker
  service: name=docker state=started
