language: go
install:
  - go get -v -tags 'fixtures acceptance' ./...
go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - tip
script: script/cibuild
after_success:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - export PATH=$PATH:$HOME/gopath/bin/
  - goveralls 2k7PTU3xa474Hymwgdj6XjqenNfGTNkO8
sudo: false
