apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-gcp-scaler
  namespace: kube-system
  labels:
    k8s-app: fluentd-gcp-scaler
    version: v0.5.1
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-gcp-scaler
  template:
    metadata:
      labels:
        k8s-app: fluentd-gcp-scaler
    spec:
      serviceAccountName: fluentd-gcp-scaler
      tolerations:
      - key: "components.gke.io/gke-managed-components"
        operator: "Exists"
      containers:
      - name: fluentd-gcp-scaler
        image: k8s.gcr.io/fluentd-gcp-scaler:0.5.2
        command:
          - /scaler.sh
          - --ds-name=fluentd-gcp-{{ fluentd_gcp_yaml_version }}
          - --scaling-policy=fluentd-gcp-scaling-policy
        env:
        # Defaults, used if no overrides are found in fluentd-gcp-scaling-policy
        - name: CPU_REQUEST
          value: 100m
        - name: MEMORY_REQUEST
          value: 200Mi
        - name: CPU_LIMIT
          value: "1"
        - name: MEMORY_LIMIT
          value: 500Mi
