---
- name: Add gpg key for docker repository.
  apt_key:
    keyserver: hkp://pgp.mit.edu:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: Create docker.list file if missing.
  file:
    path: /etc/apt/sources.list.d/docker.list
    state: touch
  changed_when: False

- name: Add entry ubuntu 14.04.
  lineinfile:
    dest: /etc/apt/sources.list.d/docker.list
    line: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
    regexp: ".*.dockerproject..*"
    state: present

- name: Update apt cache
  apt:
    update_cache: "yes"

# Pin this to version 1.9 due to some issues (probably minor...) with 1.10
- name: Install docker package.
  apt:
    name: docker-engine=1.9.1-0~trusty
    force: "yes"
    state: present

- name: Enable docker service on startup.
  service:
    name: docker
    enabled: "yes"
    state: started
