options:
  ingress:
    type: boolean
    default: true
    description: |
      Deploy the default http backend and ingress controller to handle
      ingress requests.
  labels:
    type: string
    default: ""
    description: |
      Labels can be used to organize and to select subsets of nodes in the
      cluster. Declare node labels in key=value format, separated by spaces.
  allow-privileged:
    type: string
    default: "auto"
    description: |
      Allow privileged containers to run on worker nodes. Supported values are
      "true", "false", and "auto". If "true", kubelet will run in privileged
      mode by default. If "false", kubelet will never run in privileged mode.
      If "auto", kubelet will not run in privileged mode by default, but will
      switch to privileged mode if gpu hardware is detected.
  channel:
    type: string
    default: "1.8/stable"
    description: |
      Snap channel to install Kubernetes worker services from
  require-manual-upgrade:
    type: boolean
    default: true
    description: |
      When true, worker services will not be upgraded until the user triggers
      it manually by running the upgrade action.
  kubelet-extra-args:
    type: string
    default: ""
    description: |
      Space separated list of flags and key=value pairs that will be passed as arguments to
      kubelet. For example a value like this:
        runtime-config=batch/v2alpha1=true profiling=true
      will result in kube-apiserver being run with the following options:
        --runtime-config=batch/v2alpha1=true --profiling=true
  proxy-extra-args:
    type: string
    default: ""
    description: |
      Space separated list of flags and key=value pairs that will be passed as arguments to
      kube-proxy. For example a value like this:
        runtime-config=batch/v2alpha1=true profiling=true
      will result in kube-apiserver being run with the following options:
        --runtime-config=batch/v2alpha1=true --profiling=true
