options:
  ingress:
    type: boolean
    default: true
    description: |
      Deploy the default http backend and ingress controller to handle
      ingress requests.
  labels:
    type: string
    default: ""
    description: |
      Labels can be used to organize and to select subsets of nodes in the
      cluster. Declare node labels in key=value format, separated by spaces.
  allow-privileged:
    type: string
    default: "true"
    description: |
      Allow privileged containers to run on worker nodes. Supported values are
      "true", "false", and "auto". If "true", kubelet will run in privileged
      mode by default. If "false", kubelet will never run in privileged mode.
      If "auto", kubelet will not run in privileged mode by default, but will
      switch to privileged mode if gpu hardware is detected. Pod security
      policies (PSP) should be used to restrict container privileges.
  channel:
    type: string
    default: "1.11/stable"
    description: |
      Snap channel to install Kubernetes worker services from
  require-manual-upgrade:
    type: boolean
    default: true
    description: |
      When true, worker services will not be upgraded until the user triggers
      it manually by running the upgrade action.
  kubelet-extra-args:
    type: string
    default: ""
    description: |
      Space separated list of flags and key=value pairs that will be passed as arguments to
      kubelet. For example a value like this:
        runtime-config=batch/v2alpha1=true profiling=true
      will result in kube-apiserver being run with the following options:
        --runtime-config=batch/v2alpha1=true --profiling=true
  proxy-extra-args:
    type: string
    default: ""
    description: |
      Space separated list of flags and key=value pairs that will be passed as arguments to
      kube-proxy. For example a value like this:
        runtime-config=batch/v2alpha1=true profiling=true
      will result in kube-apiserver being run with the following options:
        --runtime-config=batch/v2alpha1=true --profiling=true
  docker-logins:
    type: string
    default: "[]"
    description: |
      Docker login credentials. Setting this config allows Kubelet to pull images from
      registries where auth is required.

      The value for this config must be a JSON array of credential objects, like this:
        [{"server": "my.registry", "username": "myUser", "password": "myPass"}]
  ingress-ssl-chain-completion:
    type: boolean
    default: false
    description: |
      Enable chain completion for TLS certificates used by the nginx ingress
      controller.  Set this to true if you would like the ingress controller
      to attempt auto-retrieval of intermediate certificates.  The default
      (false) is recommended for all production kubernetes installations, and
      any environment which does not have outbound Internet access.
  nginx-image:
    type: string
    default: "auto"
    description: |
      Docker image to use for the nginx ingress controller. Auto will select an image
      based on architecture.
  default-backend-image:
    type: string
    default: "auto"
    description: |
      Docker image to use for the default backend. Auto will select an image
      based on architecture.
  snapd_refresh:
    default: "max"
    type: string
    description: |
      How often snapd handles updates for installed snaps. Setting an empty
      string will check 4x per day. Set to "max" to delay the refresh as long
      as possible. You may also set a custom string as described in the
      'refresh.timer' section here:
        https://forum.snapcraft.io/t/system-options/87
  kubelet-extra-config:
    default: "{}"
    type: string
    description: |
      Extra configuration to be passed to kubelet. Any values specified in this
      config will be merged into a KubeletConfiguration file that is passed to
      the kubelet service via the --config flag. This can be used to override
      values provided by the charm.

      Requires Kubernetes 1.10+.

      The value for this config must be a YAML mapping that can be safely
      merged with a KubeletConfiguration file. For example:
        {evictionHard: {memory.available: 200Mi}}

      For more information about KubeletConfiguration, see upstream docs:
      https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/
