sudo: false
language: go
matrix:
  include:
    - go: 1.8.x
      script:
        - go test -v -race ./...
    - go: 1.9.x
      script:
        - go test -v -race ./...
    - go: 1.10.x
      script:
        - go test -v -race ./...
    - go: 1.11.x
      script:
        - go test -v -race ./...
    - go: 1.12.x
      script:
        - go test -v -race ./...
    - go: 1.13.x
      script:
        - go test -v -race ./...
    - go: 1.14.x
      script:
        - go test -v -race ./...
    - go: 1.15.x
      script:
        - diff -u <(echo -n) <(gofmt -d .)
        - go test -v -race ./...
    - go: master
      script:
        - go test -v -race ./...
  allow_failures:
    - go: master
  fast_finish: true
