---
# Install etcd
- hosts: etcd
  sudo: yes
  roles:
    - common
    - etcd
  tags:
    - etcd

# install flannel
- hosts:
    - etcd
    - masters
    - nodes
  sudo: yes
  roles:
    - flannel
  tags:
    - flannel

# install kube master services
- hosts: masters
  sudo: yes
  roles:
    - common
    - kubernetes
    - master
  tags:
    - masters

# launch addons, like dns
- hosts: masters
  sudo: yes
  roles:
        - kubernetes-addons
  tags:
        - addons

# install kubernetes on the nodes
- hosts: nodes
  sudo: yes
  roles:
    - common
    - kubernetes
    - node
  tags:
    - nodes
