---
- hosts: all
  gather_facts: false
  sudo: yes
  roles:
    - pre-ansible
  tags:
    - pre-ansible

# Install etcd
- hosts: etcd
  sudo: yes
  roles:
    - etcd
  tags:
    - etcd

# install flannel
- hosts:
    - etcd
    - masters
    - nodes
  sudo: yes
  roles:
    - flannel
  tags:
    - flannel

# install kube master services
- hosts: masters
  sudo: yes
  roles:
    - master
  tags:
    - masters

# launch addons, like dns
- hosts: masters
  sudo: yes
  roles:
    - kubernetes-addons
  tags:
    - addons
    - dns

# install kubernetes on the nodes
- hosts: nodes
  sudo: yes
  roles:
    - node
  tags:
    - nodes
