---
# Install etcd
- hosts: etcd
  sudo: yes
  roles:
        - common
        - etcd
  tags:
        - etcd

# install flannel
- hosts:
        - etcd
        - masters
        - nodes
  sudo: yes
  roles:
        - flannel
  tags:
        - flannel

# install kube master services
- hosts: masters
  sudo: yes
  roles:
        - common
        - kubernetes
        - master
  tags:
        - masters

# install kubernetes on the nodes
- hosts: nodes
  sudo: yes
  roles:
        - common
        - kubernetes
        - node
  tags:
        - nodes
