---
- hosts: masters:minions
  sudo: yes
  roles:
    - common

- hosts: masters
  sudo: yes
  roles:
    - kubernetes
    - master

- hosts: minions
  sudo: yes
  roles:
    - kubernetes
    - minion
