ambassador:
  image: cpuguy83/docker-grand-ambassador:0.9.1
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  command: "-name dind_apiserver_1"
etcd:
  hostname: etcd
  image: gcr.io/google_containers/etcd-amd64:2.2.5
  ports: [ "4001:4001" ]
  command: >
    /usr/local/bin/etcd
    --listen-client-urls 'http://etcd:4001'
    --advertise-client-urls 'http://etcd:4001'
    --initial-cluster-state new
node:
  hostname: node
  privileged: true
  image: k8s.io/kubernetes-dind
  ports: [ "10248","10249" ]
  entrypoint:
  - bash
  - -xc
  - >
    NAME=$$(cut -f2 -d/ <<<$${APISERVER_NAME}) &&
    N=$${NAME##*_} &&
    HOSTNAME_OVERRIDE=$$(getent hosts node | cut -d' ' -f1 | sort -u | tail -1) &&
    DOCKER_NETWORK_OFFSET=0.0.$${N}.0
    exec wrapdocker bash -c "
    hyperkube kubelet
    --hostname-override=$${HOSTNAME_OVERRIDE}
    --node-labels="rack=$${N},gen=201$${N}"
    --api-servers=http://apiserver:8888
    --allow-privileged
    --cluster-dns=${DNS_SERVER_IP}
    --cluster-domain=${DNS_DOMAIN}
    --config=/var/lib/kubelet/manifests &
    hyperkube proxy
    --hostname-override=$${HOSTNAME_OVERRIDE}
    --master=http://apiserver:8888
    --conntrack-max=0
    --v=4 &
    wait \$$(jobs -p)
    "
  command: []
  environment:
  - VAR_LIB_DOCKER_SIZE=10
  - DOCKER_DAEMON_ARGS
  links:
  - etcd
  - "ambassador:apiserver"
apiserver:
  hostname: apiserver
  image: k8s.io/kubernetes-dind
  entrypoint:
  - /bin/bash
  - "-ceu"
  - >
    echo "Hostname: $$(hostname -f) ($$(hostname -f | xargs resolveip.sh))" &&
    await-health-check "-t=${DOCKER_IN_DOCKER_ETCD_TIMEOUT}" http://etcd:4001/health &&
    await-file "-t=${KUBE_KEYGEN_TIMEOUT}" /var/run/kubernetes/auth/apiserver.pem &&
    await-file "-t=${KUBE_KEYGEN_TIMEOUT}" /var/run/kubernetes/auth/service-accounts-key.pem &&
    hyperkube apiserver
    --insecure-bind-address=$$(resolveip.sh apiserver)
    --external-hostname=apiserver
    --etcd-servers=http://etcd:4001
    --insecure-port=8888
    --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,PersistentVolumeLabel
    --authorization-mode=AlwaysAllow
    --token-auth-file=/var/run/kubernetes/auth/token-users
    --basic-auth-file=/var/run/kubernetes/auth/basic-users
    --service-account-key-file=/var/run/kubernetes/auth/service-accounts-key.pem
    --service-cluster-ip-range=${SERVICE_CIDR}
    --service-node-port-range=30000-32767
    --allow-privileged
    --tls-cert-file=/var/run/kubernetes/auth/apiserver.pem
    --tls-private-key-file=/var/run/kubernetes/auth/apiserver-key.pem
    --runtime-config=api/all
    --v=4
  ports: [ "8888:8888", "6443:6443" ]
  volumes:
  - ${DOCKER_IN_DOCKER_WORK_DIR}/auth:/var/run/kubernetes/auth:ro
  links:
  - etcd
controller:
  hostname: controller
  image: k8s.io/kubernetes-dind
  entrypoint:
  - /bin/bash
  - "-ceu"
  - >
    echo "Hostname: $$(hostname -f) ($$(hostname -f | xargs resolveip.sh))" &&
    await-health-check "-t=${DOCKER_IN_DOCKER_API_TIMEOUT}" http://apiserver:8888/healthz &&
    await-file "-t=${KUBE_KEYGEN_TIMEOUT}" /var/run/kubernetes/auth/ca.pem &&
    await-file "-t=${KUBE_KEYGEN_TIMEOUT}" /var/run/kubernetes/auth/service-accounts-key.pem &&
    hyperkube controller-manager
    --address=$$(resolveip.sh controller)
    --master=http://apiserver:8888
    --service-account-private-key-file=/var/run/kubernetes/auth/service-accounts-key.pem
    --root-ca-file=/var/run/kubernetes/auth/ca.pem
    --v=4
  volumes:
  - ${DOCKER_IN_DOCKER_WORK_DIR}/auth:/var/run/kubernetes/auth:ro
  links:
  - apiserver
scheduler:
  hostname: scheduler
  image: k8s.io/kubernetes-dind
  entrypoint:
  - /bin/bash
  - "-ceu"
  - >
    echo "Hostname: $$(hostname -f) ($$(hostname -f | xargs resolveip.sh))" &&
    await-health-check "-t=${DOCKER_IN_DOCKER_API_TIMEOUT}" http://apiserver:8888/healthz &&
    hyperkube scheduler
    --address=$$(resolveip.sh scheduler)
    --master=http://apiserver:8888
    --v=4
  links:
  - apiserver
  volumes:
  - ./static-pod.json:/opt/static-pods/static-pod.json
keygen:
  image: cfssl/cfssl:latest
  entrypoint:
  - /bin/bash
  - -ec
  - |
    cd /var/run/kubernetes/auth
    echo '{"CN":"CA","key":{"algo":"rsa","size":2048}}' | cfssl gencert -initca - | cfssljson -bare ca -
    echo '{"signing":{"default":{"expiry":"43800h","usages":["signing","key encipherment","server auth","client auth"]}}}' > ca-config.json
    export ADDRESS="$$(getent hosts apiserver | awk '{ print $$1 ; exit }'),${APISERVER_SERVICE_IP},kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster.local"
    echo '{"CN":"'apiserver'","hosts":[""],"key":{"algo":"rsa","size":2048}}' | \
      cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -hostname="$${ADDRESS}" - | \
      cfssljson -bare apiserver
  volumes:
  - ${DOCKER_IN_DOCKER_WORK_DIR}/auth:/var/run/kubernetes/auth
  links:
  - apiserver
