name: config
synopsis: Modify kubeconfig files
description: "Modify kubeconfig files using subcommands like \"kubectl config set
  current-context my-context\" \n\nThe loading order follows these rules: \n\n  1.
  If the --kubeconfig flag is set, then only that file is loaded.  The flag may only
  be set once and no merging takes place.  \n  2. If $KUBECONFIG environment variable
  is set, then it is used a list of paths (normal path delimitting rules for your
  system).  These paths are merged.  When a value is modified, it is modified in the
  file that defines the stanza.  When a value is created, it is created in the first
  file that exists.  If no files in the chain exist, then it creates the last file
  in the list.  \n  3. Otherwise, ${HOME}/.kube/config is used and no merging takes
  place."
options:
- name: kubeconfig
  usage: use a particular kubeconfig file
inherited_options:
- name: alsologtostderr
  default_value: "false"
  usage: log to standard error as well as files
- name: api-version
  usage: |
    DEPRECATED: The API version to use when talking to the server
- name: as
  usage: Username to impersonate for the operation
- name: certificate-authority
  usage: Path to a cert. file for the certificate authority
- name: client-certificate
  usage: Path to a client certificate file for TLS
- name: client-key
  usage: Path to a client key file for TLS
- name: cluster
  usage: The name of the kubeconfig cluster to use
- name: context
  usage: The name of the kubeconfig context to use
- name: insecure-skip-tls-verify
  default_value: "false"
  usage: |
    If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure
- name: log-backtrace-at
  default_value: :0
  usage: when logging hits line file:N, emit a stack trace
- name: log-dir
  usage: If non-empty, write log files in this directory
- name: logtostderr
  default_value: "false"
  usage: log to standard error instead of files
- name: match-server-version
  default_value: "false"
  usage: Require server version to match client version
- name: namespace
  shorthand: "n"
  usage: If present, the namespace scope for this CLI request
- name: password
  usage: Password for basic authentication to the API server
- name: request-timeout
  default_value: "0"
  usage: |
    The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests.
- name: server
  shorthand: s
  usage: The address and port of the Kubernetes API server
- name: stderrthreshold
  default_value: "2"
  usage: logs at or above this threshold go to stderr
- name: token
  usage: Bearer token for authentication to the API server
- name: user
  usage: The name of the kubeconfig user to use
- name: username
  usage: Username for basic authentication to the API server
- name: v
  shorthand: v
  default_value: "0"
  usage: log level for V logs
- name: vmodule
  usage: |
    comma-separated list of pattern=N settings for file-filtered logging
see_also:
- kubectl
- current-context
- delete-cluster
- delete-context
- get-clusters
- get-contexts
- set
- set-cluster
- set-context
- set-credentials
- unset
- use-context
- view
