cluster.name: kubernetes-logging

node.name: ${NODE_NAME}
node.master: ${NODE_MASTER}
node.data: ${NODE_DATA}

transport.profiles.default.port: ${TRANSPORT_PORT}
http.port: ${HTTP_PORT}

path.data: /data

